var imageGallery = {
	logo:"img/logos/SVG/patri-white.svg",
	headerBackground:"img/backgrounds/appContainer_Wallpaper.jpg",
	welcomeBackground:"img/backgrounds/welcomeContainer_wallpaper.jpg",
	welcomeImage: "img/welcomeImage.jpg",
	welcomeImage1: "img/pages/miniaturas/lavozeslava.jpg",
	welcomeImage2: "img/pages/miniaturas/circe.jpg",
	welcomeImage3: "img/pages/miniaturas/narciso.jpg",
	welcomeImage4: "img/pages/miniaturas/medeacomic.jpg",
	welcomeImage5: "img/pages/miniaturas/bellaybestia.jpg",
	welcomeImage6: "img/pages/miniaturas/cuentosclasicos.jpg",
	welcomeLogo: "img/logos/SVG/patri.svg",
	welcomeArrow: "img/logos/SVG/downarrow.svg",
	imageTest:"img/pages/Dibujos y pinturas/Figuras/Figuras4.jpg",
	headerInstagram:"img/logos/SVG/instagram-white.svg",
	headerFacebook:"img/logos/SVG/facebook-white.svg",
	headerTwitter:"img/logos/SVG/twitter-white.svg",
	sectionArrow:"img/logos/SVG/leftarrow-blue.svg",
	sectionArrowRed:"img/logos/SVG/leftarrow-red.svg",
	modelovivo:"img/slider/modelovivo.jpg",
	contactMainImage:"img/patriContacto.png",
	contactPhoneImage:"img/logos/SVG/phone.svg",
	contactEmailImage:"img/logos/SVG/email.svg",
	contactTwitterImage:"img/logos/SVG/twitter-woarrow.svg",
	contactTwitterArrowImage:"img/logos/SVG/rightarrow-red.svg",
	contactFacebookImage:"img/logos/SVG/facebook.svg",
	contactInstagramImage:"img/logos/SVG/instagram.svg",
	figuras1:"img/pages/Dibujos y pinturas/Figuras/Figuras1.jpg",
	figuras2:"img/pages/Dibujos y pinturas/Figuras/Figuras2.jpg",
	figuras3:"img/pages/Dibujos y pinturas/Figuras/Figuras3.jpg",
	figuras4:"img/pages/Dibujos y pinturas/Figuras/Figuras4.jpg",
	figuras5:"img/pages/Dibujos y pinturas/Figuras/Figuras5.jpg",
	figuras6:"img/pages/Dibujos y pinturas/Figuras/Figuras6.jpg",
	figuras7:"img/pages/Dibujos y pinturas/Figuras/Figuras7.jpg",
	figuras8:"img/pages/Dibujos y pinturas/Figuras/Figuras8.jpg",
	figuras9:"img/pages/Dibujos y pinturas/Figuras/Figuras9.jpg",
	figuras10:"img/pages/Dibujos y pinturas/Figuras/Figuras10.jpg",
	circe1:"img/pages/circe/circe1.jpg",
	circe2:"img/pages/circe/circe2.jpg",
	circe3:"img/pages/circe/circe3.jpg",
	circe4:"img/pages/circe/circe4.jpg",
	circe5:"img/pages/circe/circe5.jpg",
	narciso1:"img/pages/narciso/narciso1.jpg",
	narciso2:"img/pages/narciso/narciso2.jpg",
	narciso3:"img/pages/narciso/narciso3.jpg",
	narciso4:"img/pages/narciso/narciso4.jpg",
	narciso5:"img/pages/narciso/narciso5.jpg",
	narciso6:"img/pages/narciso/narciso6.jpg",
	narciso7:"img/pages/narciso/narciso7.jpg",
	medeacomic1: "img/pages/medeacomic/medeacomic1.jpg",
	medeacomic2:"img/pages/medeacomic/medeacomic2.jpg",
	medeacomic3:"img/pages/medeacomic/medeacomic3.jpg",
	medeacomic4:"img/pages/medeacomic/medeacomic4.jpg",
	lavozeslava1:"img/pages/lavozeslava/vozeslava1.jpg",
	lavozeslava2:"img/pages/lavozeslava/vozeslava2.jpg",
	lavozeslava3:"img/pages/lavozeslava/vozeslava3.jpg",
	lavozeslava4:"img/pages/lavozeslava/vozeslava4.jpg",
	lavozeslava5:"img/pages/lavozeslava/vozeslava5.jpg",
	bellaybestia1:"img/pages/bellaybestia/bellabestia1.jpg",
	bellaybestia2:"img/pages/bellaybestia/bellabestia2.jpg",
	bellaybestia3:"img/pages/bellaybestia/bellabestia3.jpg",
	bellaybestia4:"img/pages/bellaybestia/bellabestia4.jpg",
	culpables1: "img/pages/culpables/culpables1.jpg",
	culpables2: "img/pages/culpables/culpables2.jpg",
	culpables3: "img/pages/culpables/culpables3.jpg",
	culpables4: "img/pages/culpables/culpables4.jpg",
	culpables5: "img/pages/culpables/culpables5.jpg",
	culpables6: "img/pages/culpables/culpables6.jpg",
	eulienkantua1: "img/pages/Posters/Eulien kantua/eulienkantua1.jpg",
	eulienkantua2: "img/pages/Posters/Eulien kantua/eulienkantua2.jpg",
	eulienkantua3: "img/pages/Posters/Eulien kantua/eulienkantua3.jpg",
	eulienkantua4: "img/pages/Posters/Eulien kantua/eulienkantua4.jpg",
	eulienkantua5: "img/pages/Posters/Eulien kantua/eulienkantua5.jpg",
	eulienkantua6: "img/pages/Posters/Eulien kantua/eulienkantua6.jpg",
	cuentosclasicos1:"img/pages/cuentosclasicos/cuentos1.jpg",
	cuentosclasicos2:"img/pages/cuentosclasicos/cuentos2.jpg",
	cuentosclasicos3:"img/pages/cuentosclasicos/cuentos3.jpg",
	cuentosclasicos4:"img/pages/cuentosclasicos/cuentos4.jpg",
	cuentosclasicos5:"img/pages/cuentosclasicos/cuentos5.jpg",
	cuentosclasicos6:"img/pages/cuentosclasicos/cuentos6.jpg",
	cuentosclasicos7:"img/pages/cuentosclasicos/cuentos7.jpg",
	editorialPageImageSrc:"img/pages/Dibujos y pinturas/Figuras/Figuras4.jpg",
	adultoThumbnailImageSrc:"img/pages/Dibujos y pinturas/Figuras/Figuras4.jpg",
	adultoPageImageSrc:"img/pages/Dibujos y pinturas/Figuras/Figuras4.jpg",
	lavozeslavaThumbnailImageSrc:"img/pages/miniaturas/vozeslavaminiatura.jpg",
	circeThumbnailImageSrc:"img/pages/miniaturas/circeminiatura.jpg",
	narcisoThumbnailImageSrc:"img/pages/miniaturas/narcisominiatura.jpg",
	medeacomicThumbnailImageSrc:"img/pages/miniaturas/medeacomicminiatura.jpg",
	labellaylabestiaThumbnailImageSrc: "img/pages/miniaturas/bellaybestia.jpg",
	cuentosclasicosThumbnailImageSrc: "img/pages/miniaturas/cuentosminiatura.jpg",
	infantilThumbnailImageSrc:"img/pages/Dibujos y pinturas/Figuras/Figuras4.jpg",
	infantilPageImageSrc:"img/pages/Dibujos y pinturas/Figuras/Figuras4.jpg",
	elninoylacaracolaThumbnailImageSrc:"img/pages/Dibujos y pinturas/Figuras/Figuras4.jpg",
	dibujosypinturasPageImageSrc:"img/pages/Dibujos y pinturas/Figuras/Figuras4.jpg",
	libretasThumbnailImageSrc:"img/pages/Dibujos y pinturas/Figuras/Figuras4.jpg",
	figurasThumbnailImageSrc:"img/pages/Dibujos y pinturas/Figuras/Figuras4.jpg",
	postersPageImageSrc:"img/pages/Dibujos y pinturas/Figuras/Figuras4.jpg",
	eulienkantuaThumbnailImageSrc:"img/pages/Posters/Eulien kantua/eulienkantua1.jpg",
	shakespeareThumbnailImageSrc:"img/pages/Dibujos y pinturas/Figuras/Figuras4.jpg",
	retratosPageImageSrc:"img/pages/culpables/culpables1.jpg",
	culpablesThumbnailImageSrc:"img/pages/culpables/culpables1.jpg",
	personalesThumbnailImageSrc:"img/pages/Dibujos y pinturas/Figuras/Figuras4.jpg"
};